export const scheduleTypes = {
  GET_ALL_APPOINTMENTS_REQUEST: 'GET_ALL_APPOINTMENTS_REQUEST',
  GET_ALL_APPOINTMENTS_SUCCESS: 'GET_ALL_APPOINTMENTS_SUCCESS',
  GET_ALL_APPOINTMENTS_FAILURE: 'GET_ALL_APPOINTMENTS_FAILURE',

  CREATE_APPOINTMENT_REQUEST: 'CREATE_APPOINTMENT_REQUEST',
  CREATE_APPOINTMENT_SUCCESS: 'CREATE_APPOINTMENT_SUCCESS',
  CREATE_APPOINTMENT_FAILURE: 'CREATE_APPOINTMENT_FAILURE',

  UPDATE_APPOINTMENT_REQUEST: 'UPDATE_APPOINTMENT_REQUEST',
  UPDATE_APPOINTMENT_SUCCESS: 'UPDATE_APPOINTMENT_SUCCESS',
  UPDATE_APPOINTMENT_FAILURE: 'UPDATE_APPOINTMENT_FAILURE',

  DELETE_APPOINTMENT_REQUEST: 'DELETE_APPOINTMENT_REQUEST',
  DELETE_APPOINTMENT_SUCCESS: 'DELETE_APPOINTMENT_SUCCESS',
  DELETE_APPOINTMENT_FAILURE: 'DELETE_APPOINTMENT_FAILURE',

  SET_SCHEDULE_VIEW: 'SET_SCHEDULE_VIEW',
  SET_SCHEDULE_SELECTED_DATE: 'SET_SCHEDULE_SELECTED_DATE',
  SET_SCHEDULE_FILTERS: 'SET_SCHEDULE_FILTERS',
  RESET_SCHEDULE_FILTERS: 'RESET_SCHEDULE_FILTERS',
};
