export const specialtyTypes = {
  GET_ALL_SPECIALTIES_REQUEST: 'GET_ALL_SPECIALTIES_REQUEST',
  GET_ALL_SPECIALTIES_SUCCESS: 'GET_ALL_SPECIALTIES_SUCCESS',
  GET_ALL_SPECIALTIES_FAILURE: 'GET_ALL_SPECIALTIES_FAILURE',

  CREATE_SPECIALTY_REQUEST: 'CREATE_SPECIALTY_REQUEST',
  CREATE_SPECIALTY_SUCCESS: 'CREATE_SPECIALTY_SUCCESS',
  CREATE_SPECIALTY_FAILURE: 'CREATE_SPECIALTY_FAILURE',

  UPDATE_SPECIALTY_REQUEST: 'UPDATE_SPECIALTY_REQUEST',
  UPDATE_SPECIALTY_SUCCESS: 'UPDATE_SPECIALTY_SUCCESS',
  UPDATE_SPECIALTY_FAILURE: 'UPDATE_SPECIALTY_FAILURE',

  DELETE_SPECIALTY_REQUEST: 'DELETE_SPECIALTY_REQUEST',
  DELETE_SPECIALTY_SUCCESS: 'DELETE_SPECIALTY_SUCCESS',
  DELETE_SPECIALTY_FAILURE: 'DELETE_SPECIALTY_FAILURE',
};
