export const patientTypes = {
  GET_ALL_PATIENTS_REQUEST: 'GET_ALL_PATIENTS_REQUEST',
  GET_ALL_PATIENTS_SUCCESS: 'GET_ALL_PATIENTS_SUCCESS',
  GET_ALL_PATIENTS_FAILURE: 'GET_ALL_PATIENTS_FAILURE',

  CREATE_PATIENT_REQUEST: 'CREATE_PATIENT_REQUEST',
  CREATE_PATIENT_SUCCESS: 'CREATE_PATIENT_SUCCESS',
  CREATE_PATIENT_FAILURE: 'CREATE_PATIENT_FAILURE',
  CREATE_PATIENT: 'CREATE_PATIENT',

  UPDATE_PATIENT_REQUEST: 'UPDATE_PATIENT_REQUEST',
  UPDATE_PATIENT_SUCCESS: 'UPDATE_PATIENT_SUCCESS',
  UPDATE_PATIENT_FAILURE: 'UPDATE_PATIENT_FAILURE',
  UPDATE_PATIENT: 'UPDATE_PATIENT',

  DELETE_PATIENT_REQUEST: 'DELETE_PATIENT_REQUEST',
  DELETE_PATIENT_SUCCESS: 'DELETE_PATIENT_SUCCESS',
  DELETE_PATIENT_FAILURE: 'DELETE_PATIENT_FAILURE',
  DELETE_PATIENT: 'DELETE_PATIENT',
};
