export const queueTypes = {
  GET_QUEUE_REQUESTS_REQUEST: 'GET_QUEUE_REQUESTS_REQUEST',
  GET_QUEUE_REQUESTS_SUCCESS: 'GET_QUEUE_REQUESTS_SUCCESS',
  GET_QUEUE_REQUESTS_FAILURE: 'GET_QUEUE_REQUESTS_FAILURE',

  CREATE_QUEUE_REQUEST_REQUEST: 'CREATE_QUEUE_REQUEST_REQUEST',
  CREATE_QUEUE_REQUEST_SUCCESS: 'CREATE_QUEUE_REQUEST_SUCCESS',
  CREATE_QUEUE_REQUEST_FAILURE: 'CREATE_QUEUE_REQUEST_FAILURE',

  UPDATE_QUEUE_REQUEST_REQUEST: 'UPDATE_QUEUE_REQUEST_REQUEST',
  UPDATE_QUEUE_REQUEST_SUCCESS: 'UPDATE_QUEUE_REQUEST_SUCCESS',
  UPDATE_QUEUE_REQUEST_FAILURE: 'UPDATE_QUEUE_REQUEST_FAILURE',

  DELETE_QUEUE_REQUEST_REQUEST: 'DELETE_QUEUE_REQUEST_REQUEST',
  DELETE_QUEUE_REQUEST_SUCCESS: 'DELETE_QUEUE_REQUEST_SUCCESS',
  DELETE_QUEUE_REQUEST_FAILURE: 'DELETE_QUEUE_REQUEST_FAILURE',
};
