export const vacancyTypes = {
  GET_ALL_VACANCIES_REQUEST: 'GET_ALL_VACANCIES_REQUEST',
  GET_ALL_VACANCIES_SUCCESS: 'GET_ALL_VACANCIES_SUCCESS',
  GET_ALL_VACANCIES_FAILURE: 'GET_ALL_VACANCIES_FAILURE',

  CREATE_VACANCY_REQUEST: 'CREATE_VACANCY_REQUEST',
  CREATE_VACANCY_SUCCESS: 'CREATE_VACANCY_SUCCESS',
  CREATE_VACANCY_FAILURE: 'CREATE_VACANCY_FAILURE',

  UPDATE_VACANCY_REQUEST: 'UPDATE_VACANCY_REQUEST',
  UPDATE_VACANCY_SUCCESS: 'UPDATE_VACANCY_SUCCESS',
  UPDATE_VACANCY_FAILURE: 'UPDATE_VACANCY_FAILURE',

  DELETE_VACANCY_REQUEST: 'DELETE_VACANCY_REQUEST',
  DELETE_VACANCY_SUCCESS: 'DELETE_VACANCY_SUCCESS',
  DELETE_VACANCY_FAILURE: 'DELETE_VACANCY_FAILURE',
};
