export const professionalTypes = {
  GET_ALL_PROFESSIONALS_REQUEST: 'GET_ALL_PROFESSIONALS_REQUEST',
  GET_ALL_PROFESSIONALS_SUCCESS: 'GET_ALL_PROFESSIONALS_SUCCESS',
  GET_ALL_PROFESSIONALS_FAILURE: 'GET_ALL_PROFESSIONALS_FAILURE',

  CREATE_PROFESSIONAL_REQUEST: 'CREATE_PROFESSIONAL_REQUEST',
  CREATE_PROFESSIONAL_SUCCESS: 'CREATE_PROFESSIONAL_SUCCESS',
  CREATE_PROFESSIONAL_FAILURE: 'CREATE_PROFESSIONAL_FAILURE',

  UPDATE_PROFESSIONAL_REQUEST: 'UPDATE_PROFESSIONAL_REQUEST',
  UPDATE_PROFESSIONAL_SUCCESS: 'UPDATE_PROFESSIONAL_SUCCESS',
  UPDATE_PROFESSIONAL_FAILURE: 'UPDATE_PROFESSIONAL_FAILURE',

  DELETE_PROFESSIONAL_REQUEST: 'DELETE_PROFESSIONAL_REQUEST',
  DELETE_PROFESSIONAL_SUCCESS: 'DELETE_PROFESSIONAL_SUCCESS',
  DELETE_PROFESSIONAL_FAILURE: 'DELETE_PROFESSIONAL_FAILURE',
};
